' Developer Express Code Central Example:
' How to provide a custom template for series labels
' 
' The following example demonstrates how to change the appearance of series
' labels.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E1258
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace CustomLabelTemplate.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As CustomLabelTemplate.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New CustomLabelTemplate.Properties.Settings())), CustomLabelTemplate.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return CustomLabelTemplate.Properties.Settings.defaultInstance
            End Get
        End Property
    End Class
End Namespace
